### ISSUE TITLE
Précisions sur l'API

### ISSUE THREAD

**Issue by Hugal31** [ApoucheZia/zia#12]
Bonjour, j'aurais quelques questions sur l'API :

- Que sont censés faire IHttpRequest::getUriParameter ainsi que d'autres méthodes si la clé n'est pas connue ?
- Pourquoi HttpHeader se nomme t'il ainsi sans 's', alors qu'il est stocké dans des variables appelées "headers" un peu partout ?
- Est-ce que IHttpMessage::setHeaders et IHttpMessage::setBody doivent delete l'ancien body / header ?
Si la réponse est oui, HttpRequest et HttpResponse devraient également les delete lors de la destruction. 
- Qu'est-ce que HttpMessage::getVersion doit renvoyer ? Par exemple "1.1" ou "HTTP/1.1" ?
- Est-ce que les paramètres URI doivent être encodé / décodés par HttpRequest::getUriParameter et HttpRequest::setUriParameter, ou on laisse encodé ?
Remarque : de toute façon, aucun des modules ne devrait avoir besoin des paramètres URI. Je ne vois donc pas le besoin des méthodes HttpRequest::\*UriParameter*.

**Comment by Calion54** [comment]
Bonjour,

Alors getUriParameter a pour but de renvoyer les paramètre de l'url get par exemple localhost/sets/?toto=tata&tata=tata
donc ça va directement permettre de récupérer la valeur en fonction de la clé.
Il y a une méthode qui retourne true ou false si la clé existe ou pas.

Effectivement, je ne vois pas pourquoi nous avons mis des 's' pour ces methodes là.

Je pense que setBody et setHeader doivent delete les anciens pointeur car il n'y a plus d'utilité a les utiliser

En ce qui concerne la version, c'est le parser dans httpRequest qui la récupère directement dans la requête donc c'est "HTTP/1.1"

En ce qui concerne l'encodage des url, ceci est intéressant, nous ne l'avons pas pris en compte donc ceci doit être effectué par le module/serveur
ps : nous l'avons rajouté si des personnes souhaitent réalisé d'autre module.

J'espère que j'ai répondu a tes intérrogations

**Comment by Hugal31** [comment]
Bonjour.

Merci d'avoir répondu à mes interrogations. Je fait une pull-request pour IHttpMessage::setHeader / setBody.

Je pense qu'il est important de définir le comportement de getUriParameter si la clef n'existe pas. Elle lance std::exception, std::out_of_range ou comportement indéfini ? Je préconise std::out_of_range.

Je pense également qu'il serait judicieux de noter ces précisions dans la documentation.

**Comment by Calion54** [comment]
D'accord je fais parvenir cette information au reste de l'équipe. Merci :)

**Comment by Calion54** [comment]
Voila. la methode getUriParameter throw une exception quand la clé n'existe pas.

**Comment by Hugal31** [comment]
Merci pour le commit, mais il était inutile :') ```std::map::at``` renvoie déjà ```std::out_of_range("at")``` si la clef n'existe pas.
Ce que je voulais dire, c'était de le faire apparaître dans la documentation, par exemple avec un ```\throw```

**Comment by Calion54** [comment]
ah ok^^ je n'avais pas compris. La doc ce n'est pas moi qui la met à jour.
Il faudra attendre ceux qui s'occupe de ça (ils sont en part-time) donc ce soir :)
